CREATE DATABASE TripPlanner;

GO
USE TripPlanner;

--First, create tables
CREATE TABLE [User](
FullName NVARCHAR(60) PRIMARY KEY NOT NULL,
HomeAddress NVARCHAR(75) NOT NULL,
PhoneNumber NVARCHAR(15),
DOB DATE NOT NULL,
);

CREATE TABLE Passport(
PassportNum INT PRIMARY KEY NOT NULL,
PassportAddress NVARCHAR(75) NOT NULL,
ExpDate DATE NOT NULL
);

CREATE TABLE Trip(
TripID INT PRIMARY KEY NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE,
StartDestination NVARCHAR(25) NOT NULL,
EndDestination NVARCHAR(25),
Budget REAL NOT NULL,
TravelMode NVARCHAR(10) NOT NULL,
);

CREATE TABLE Hotel(
HotelName NVARCHAR(50) PRIMARY KEY NOT NULL,
HotelAddress NVARCHAR(50) NOT NULL,
HotelPhone NVARCHAR(15) NOT NULL,
CheckInDate DATETIME NOT NULL,
CheckOutDate DATETIME NOT NULL,
RoomAndTax REAL NOT NULL
);

GO
--Next, Add Foreign Keys
ALTER TABLE [User]
ADD PassportID INT FOREIGN KEY REFERENCES Passport(PassportNum)
ALTER TABLE [User]
ADD VacationID INT FOREIGN KEY REFERENCES Trip(TripID)
ALTER TABLE [User]
ADD HotelInfo NVARCHAR(50) FOREIGN KEY REFERENCES Hotel(HotelName)

ALTER TABLE Passport
ADD UserInfo NVARCHAR(60) FOREIGN KEY REFERENCES [User](FullName)

ALTER TABLE Trip
ADD UserName NVARCHAR(60) FOREIGN KEY REFERENCES [User](FullName)
ALTER TABLE Trip
ADD VacaID INT FOREIGN KEY REFERENCES Trip(TripID)

ALTER TABLE Hotel
ADD GuestName NVARCHAR(60) FOREIGN KEY REFERENCES [User](FullName)
ALTER TABLE Hotel
ADD StayID INT FOREIGN KEY REFERENCES Trip(TripID)